### ISSUE TITLE
 Unable to see Documentation for different version

### ISSUE THREAD

**Issue by gabrielmcf** [rwynn/monstache-site#12]
Sometimes we want to check a change in the configurations, or see if something is working in one version and not in another but the site has only the last version configs.

**Comment by rwynn** [comment]
Thanks that is a good suggestion.  I will think about.  At this point you may be able to write a script that generates the site for each commit.  If the script does a git checkout of previous commit it can run `mkdocs build -c` on that version and then copy the results to a folder with the current git timestamp in it. The script would just need to do that in a loop going back over the commits.  That way you can generate the docs as they were at the time.  You would end up with a list of directories by timestamp that you could open in your browser and compare.

**Comment by gabrielmcf** [comment]
Great suggestion! I've seen you write some breaking changes in the documentation. This is working great for me now!
