### ISSUE TITLE
I want to express all the collections in a database。How should I write direct-read-namespaces

### ISSUE THREAD

**Issue by snoopy83101** [rwynn/monstache-site#2]
At the first synchronization
I want to express all the collections in a database。
How should I write direct-read-namespaces

**Comment by rwynn** [comment]
Currently you have to list each one explicitly.

**Comment by richiarora** [comment]
I had a question : Can new collections added to database be automatically sent to elasticsearch ? considering i use wild card like : namespace-regex = '^mydb\.(*\$cmd)$' so ideally it will search through all the collections. will it cater to new collections that i add?

2- Sometimes i have observed collections are not getting synced at all.

**Comment by rwynn** [comment]
Hi it doesn’t actually maintain a list of collections but rather listens for all changes in Mongodb and then tests the namespace of the change against your regex. So yes it would pick up new collections dynamically. 

Simply use  ^mydb\. as your regex. 

If a collection is not getting synced make sure it’s db.col is a match against your configured regexes. Or remove those regexes and sync all changes.

**Comment by rwynn** [comment]
There should be a backslash  before the . In the regex. In my previous comment. It got removed when I posted.

**Comment by richiarora** [comment]
hi thanks for quick reply so i used `namespace-regex = '^my-database\.'` or namespace-regex = `^my-database\.([A-Za-z0-9\-]*\$cmd)$`
Collections in my database are test1 and test2
and also tried removing regex completely  just to push all data to elasticsearch but in logs i only see details related to monstache_stats index.

PS there are no indexes defined in the elasticsearch i was hoping for exception in logs that index not found etc

**Comment by rwynn** [comment]
Have you also put all the namespaces that you currently have in the direct-read-namespaces array?  If you are syncing for the first time you need to do direct reads. Or replay the oplog. By default monstache just tails the oplog for new changes.

**Comment by rwynn** [comment]
Also if you have a dash in your db name then you need to escape it in the regex.

**Comment by richiarora** [comment]
hi thanks for pointing out the error the replay=true did the trick. 
Also wanted to know that will this be capable of working in production on sharded environment ?

**Comment by rwynn** [comment]
It does have support for sharded clusters. See the docs for mongo-url and mongo-config-url. 

https://rwynn.github.io/monstache-site/config/

You would need to evaluate if this would work in your production setup.  I don’t have any references at this time.

**Comment by richiarora** [comment]
hi i really admire your quick responses to all my queries.
Here's another one : 
I am trying to sync the gridfs files to elasticsearch
I have installed ingest plugin as i am using version 6.2.2

My configuration file has : 
namespace-regex = '^(my\-database\.collection1|myGridfsDb)$'
#in above line i have defined another database where there is collection fs.files and fs.chunks
replay=true
resume=true
index-files = true
file-highlighting = true
file-namespaces = ["myGridfsDb.fs.files"]
direct-read-namespaces = ["myGridfsDb.fs"]
#so i have used possibly all options still i dont see files being submitted to ES to already present index : mygridfsdb.fs.files

I know it is kind of configuration problem only.
My requirement is to load all the present docs to elasticsearch there are few records only.

`TRACE 2018/03/13 20:28:57 PUT /_ingest/pipeline/attachment HTTP/1.1
Host: localhost:32774
User-Agent: elastic/6.1.8 (darwin-amd64)
Transfer-Encoding: chunked
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

59
{"description":"Extract file information","processors":[{"attachment":{"field":"file"}}]}
0


TRACE 2018/03/13 20:28:57 HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8

{"acknowledged":true}`
