### ISSUE TITLE
Bulk API - Several Records at Once Capability?

### ISSUE THREAD

**Issue by jag959** [rwynn/monstache-site#3]
Hello.

First, thank you for this application.

Question: Is there a way to specify that Monstache grabs a large volume of documents at once and then posts the documents to ElasticSearch?

I have the settings below in my config., but have over 1 million documents to send daily and it's taken roughly 10 min for 140 documents.  The transfer is between 2 AWS EC2 instances on the same subnet so network is optimal.

Thanks for any assistance.

```
# Bulk index request to elasticsearch will be forced when the buffer reaches the given number of documents.
elasticsearch-max-docs = 1

# Bulk index request to elasticsearch will be forced when the buffer reaches the given number of bytes.
elasticsearch-max-bytes = 1

# Bulk index request to elasticsearch will be forced when a request has not been made in the given number of seconds.
elasticsearch-max-seconds = 1
```

**Comment by rwynn** [comment]
With those settings you are sending each doc in its own request.  By default it sends 100 at a time or less if they are coming slowly from MongoDB. Use verbose to see the bulk request getting generated. 

Those numbers you posted sound ridiculously low. I’ve never seen that. Are you using direct reads or just oplog.

**Comment by rwynn** [comment]
Put the max-docs to 1000, max-seconds to 10 and remove max-bytes. Then run with direct-read-namespaces = [“mydb.mycol”] replacing with the name of your db and collection that you want to copy.  Use verbose to see the requests as they are sent.

**Comment by jag959** [comment]
Hi Ryan,

I made the changes, and it still seems to go slowly. Here is my entire config with user/pass/hosts removed.

I noticed this 'single thread' reference at start of verbose mode (below).  Maybe I have MongoDB set-up incorrectly?

```
INFO 2018/04/01 19:14:46 Successfully connected to MongoDB version 3.6.3
INFO 2018/04/01 19:14:46 Successfully connected to Elasticsearch version 5.6.8
INFO 2018/04/01 19:14:46 Direct read parallel collection scan is ON
INFO 2018/04/01 19:14:46 Entering event loop
INFO 2018/04/01 19:14:46 Sending systemd READY=1
INFO 2018/04/01 19:14:46 Systemd notification not supported (i.e. NOTIFY_SOCKET is unset)
INFO 2018/04/01 19:14:46 Parallel collection scan command returned 1/10 cursors requested for agility-xxxx.invoicesMaster
INFO 2018/04/01 19:14:46 Only 1 cursor available for collection scan in this storage engine
INFO 2018/04/01 19:14:46 Reverting to single-threaded collection read
```

**toml config-**

```
# compress requests to Elasticsearch
gzip = true

# generate indexing statistics
stats = true

# index statistics into Elasticsearch
index-stats = true

# connect to MongoDB using the following URL (url encode special characters)
mongo-url = "mongodb:/xxxx:xxxx@localhost:27017"

# use the following PEM file for connections to MongoDB
# mongo-pem-file = "/path/to/mongoCert.pem"

# disable PEM validation
# mongo-validate-pem-file = false

# connect to the Elasticsearch REST API at the following URLs
elasticsearch-urls = ["http://0.0.0.0:9200"]

# use the following user name for Elasticsearch basic auth
elasticsearch-user = "XXXX"

# use the following password for Elasticsearch basic auth
elasticsearch-password = "XXXX"

# use 10 go routines concurrently pushing documents to Elasticsearch
elasticsearch-max-conns = 200

# use the following PEM file to connections to Elasticsearch
# elasticsearch-pem-file = "/path/to/elasticCert.pem"

# validate connections to Elasticsearch
#elastic-validate-pem-file = true

# propogate dropped collections in MongoDB as index deletes in Elasticsearch
dropped-collections = true

# propogate dropped databases in MongoDB as index deletes in Elasticsearch
dropped-databases = true

# do not start processing at the beginning of the MongoDB oplog
replay = false

# resume processing from a timestamp saved in a previous run
resume = true

# do not validate that progress timestamps have been saved
resume-write-unsafe = false

# override the name under which resume state is saved
resume-name = "default"

# include documents whose namespace matches the following pattern
# namespace-regex = '^mydb\.(mycollection|\$cmd)$'

# exclude documents whose namespace matches the following pattern
# namespace-exclude-regex = '^mydb\.(ignorecollection|\$cmd)$'

# turn on indexing of GridFS file content
# index-files = true

# turn on search result highlighting of GridFS content
# file-highlighting = true

# index GridFS files inserted into the following collections
# file-namespaces = ["users.fs.files"]

# print detailed information including request traces
verbose = true

# enable clustering mode
# cluster-name = ''

# do a full-sync of the following collections
direct-read-namespaces = ["agility-xxxxx.invoicesMaster"]

# do not exit after full-sync, rather continue tailing the oplog
exit-after-direct-reads = false

# Failed request to elasticsearch will be retried with an exponential backoff policy. The policy is set with an initial timeout of 50 ms, an exponential factor of 2, and a max wait of 20 seconds.
elasticsearch-retry = true

# Bulk index request to elasticsearch will be forced when the buffer reaches the given number of documents.
elasticsearch-max-docs = 1000

# Bulk index request to elasticsearch will be forced when the buffer reaches the given number of bytes.
# elasticsearch-max-bytes = 1

# Bulk index request to elasticsearch will be forced when a request has not been made in the given number of seconds.
elasticsearch-max-seconds = 10
```

**Comment by rwynn** [comment]
Elastic max conns is maybe high at 200. That is go routines. Default is 10. 

What do the stats report. Seems you have that turned on. Maybe don’t index those into ES but note what they are.

**Comment by rwynn** [comment]
That single thread reference is probably because you use WiredTiger storage engine. It’s the default for MongoDB (nothing you are doing wrong) but it does not yet support more than 1 cursor for parallel collection scans. Hopefully they will fix that in future version of MongoDB. The previous default engine - mmapv1 - supports multi cursor parallel reads of a single collection.

**Comment by jag959** [comment]
With the changes below it sped up a bit.  I was getting 30 docs in 10 min, and now 125 in 10min.  I have over 1 million so I need more throughput.  I don't know what else to do.

I may explore another route of exporting the documents and using ES bulk api to submit large files.  Using the file to bulk API method, I had been submitting 1000s per few seconds.

I set Elastic max conns to 10.

Set these also to false:

**compress requests to Elasticsearch**
gzip = false

**generate indexing statistics**
stats = false

**index statistics into Elasticsearch**
index-stats = false

**Comment by rwynn** [comment]
Hi Jason. Not sure what is going on. Monstache uses the ES bulk API at /_bulk to index documents.  You should be getting much better performance. Have you tried Monstache on a single machine with MongoDB and ES installed locally just for reference?  In my testing I don’t have to wait more than a few minutes to sync a million docs using direct reads.

**Comment by jag959** [comment]
I may try that single instance approach.  Note, each document is "wide" (1200 fields.)  Think that is an issue?

**Comment by rwynn** [comment]
That's interesting about the ~1200 fields.  Maybe you could try changing the following option:

```
# normally this defaults to 500 but since these documents are large
direct-read-batch-size = 16
```

**Comment by rwynn** [comment]
You also might need to up the max bytes if the docs are large to force multiple in a bulk request. 

16384 Bytes is the default max for the entire bulk request. So adjust accordingly so that it’s large enough to fit multiple docs. 

Maybe set to 500000.

**Comment by rwynn** [comment]
Did you discover what the bottleneck was?

**Comment by rwynn** [comment]
@jag959 I tried a quick test with wide documents.  Granted this is on a vagrant vm with both mongodb and elasticsearch installed together and the document values are just integers.

```
rs1:PRIMARY> use test;
switched to db test
rs1:PRIMARY> db.test.count()
115950
// each document is 200 fields wide like { "0": 0, ... "199": 199 }
```

```
vagrant@debian-8:~/go$ time bin/monstache -direct-read-namespace test.test -exit-after-direct-reads
INFO 2018/04/04 21:51:00 Successfully connected to MongoDB version 3.6.3
INFO 2018/04/04 21:51:00 Successfully connected to Elasticsearch version 6.2.1
INFO 2018/04/04 21:51:00 Direct read parallel collection scan is ON
INFO 2018/04/04 21:51:00 Entering event loop
INFO 2018/04/04 21:51:00 Parallel collection scan command returned 10/10 cursors requested for test.test
INFO 2018/04/04 21:51:00 Starting 10 go routines to read test.test
INFO 2018/04/04 21:51:46 Shutting down

real    0m46.468s
user    1m26.484s
sys     0m6.360s
```
```
vagrant@debian-8:~/go$ curl localhost:9200/test.test/_count?pretty
{
  "count" : 115950,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  }
}
```
So I guess it's reading and indexing those at around 2400 per second.  It is using 10 go routines though, and that's because my mongo database is setup with mmapv1 as the storage engine.  But it does seem to be much different from your results, so I'm not sure what could be going on other than document size and network latency differences.

**Comment by rwynn** [comment]
Also, make sure you are only using `verbose` for debugging purposes.  That logs a trace of every bulk request.

**Comment by rwynn** [comment]
@jag959 it looks like the Elasticsearch default limit on fields in an index is 1000.  Are you increasing that to fit these wide documents with 1200 fields via `index.mapping.total_fields.limit`?

I think it's possible that this may be the cause of the slowdown.  It also could be that documents with more than 1000 fields are failing and thus it looks like indexing is slow (only smaller documents getting through to Elasticsearch).  If you don't need all of these fields you can use a javascript mapping function in monstache to omit fields that you don't need.

**Comment by jag959** [comment]
Hi Ryan,

Apologies for delay in response.  I had not had much time to try anything new that you had sent.  I do have ES configured to allow more than 1,000 fields.

I’m not sure when I’ll be able to get back in this.

Thanks for you help.
